In [1]:
import pandas as pd
import numpy as np
import math

import matplotlib.pyplot as plt

In [2]:
#CONVERT CARTESIAN TO POLAR
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)

# Operaciones Basicas con Vectores

In [18]:
V = np.array([6j, 8, -1+2j, 4])
W = np.array([14-1J, 0, 4+2j, 3j])

V_0 = np.array([0, 0, 0, 0])

#OPERACIONES BASICAS
print('Suma de vectores: ', V + W)
print('Suma de vectores: ', W + V)
print('Suma con vector cero: ', V, V + V_0)
print('')

#COMPROBAR ESPACIO VECTORIAL COMPLEJO
V = np.array([[5 + 4j, 3 - 2j], [1j, -4 + 2j]])
W = np.array([[0 + 2j, -3 - 2j], [8, -4 - 2j]])
Y = np.array([[1, -3 - 2j], [10j, -4 - 2j]])
Z_0 = np.array([[0, 0], [0, 0]])
c1 = 4 - 2j
c2 = 10 + 2j

print('Conmutatividad de la adición:\n', V + W, '\n', W + V, '\n')
print('Asociatividad de la adición:\n', (V + W) + Y, '\n', V + (W + Y), '\n')
print('Identidad aditiva:\n', V + Z_0, '\n', V, '\n')
print('Inverso aditivo:\n', V + -(V), '\n')
print('Identidad multiplicativa:\n', V, '\n', 1 * V, '\n')
print('Multiplicación escalar:\n', c1 * (c2 * V), '\n', (c1 * c2) * V, '\n')
print('Multiplicación escalar se distribuye sobre adicion:\n', c1 * (V + W), '\n', c1 * V + c1 * W, '\n')
print('Multiplicación escalar se distribuye sobre adicion compleja:\n', (c1 + c2) * V, '\n', c1 * V + c2 * V, '\n')

Suma de vectores:  [14.+5.j  8.+0.j  3.+4.j  4.+3.j]
Suma de vectores:  [14.+5.j  8.+0.j  3.+4.j  4.+3.j]
Suma con vector cero:  [ 0.+6.j  8.+0.j -1.+2.j  4.+0.j] [ 0.+6.j  8.+0.j -1.+2.j  4.+0.j]

Conmutatividad de la adición:
 [[ 5.+6.j  0.-4.j]
 [ 8.+1.j -8.+0.j]] 
 [[ 5.+6.j  0.-4.j]
 [ 8.+1.j -8.+0.j]] 

Asociatividad de la adición:
 [[  6. +6.j  -3. -6.j]
 [  8.+11.j -12. -2.j]] 
 [[  6. +6.j  -3. -6.j]
 [  8.+11.j -12. -2.j]] 

Identidad aditiva:
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 

Inverso aditivo:
 [[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]] 

Identidad multiplicativa:
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 
 [[ 5.+4.j  3.-2.j]
 [ 0.+1.j -4.+2.j]] 

Multiplicación escalar:
 [[ 268.+116.j  108.-124.j]
 [  12. +44.j -152.+136.j]] 
 [[ 268.+116.j  108.-124.j]
 [  12. +44.j -152.+136.j]] 

Multiplicación escalar se distribuye sobre adicion:
 [[ 32.+14.j  -8.-16.j]
 [ 34.-12.j -32.+16.j]] 
 [[ 32.+14.j  -8.-16.j]
 [ 34.-12.j -32.+16.j]] 

Multi

# Operaciones con matrices cuadradas

In [28]:
Q = np.array([[4j, 8 - 1j, 6j], [2, -4 + 4j, 10 - 6j], [10 - 1j, -2 - 2j, 3]])
print(Q.shape)
print('Ejemplo: \n', Q, '\n')
print('Transpuesta: \n', Q.T, '\n')
print('Conjugada: \n', Q.conjugate(), '\n')
print('Adjunta: \n', np.matrix(Q).getH(), '\n\n', Q.T.conjugate(), '\n\n', Q.conjugate().T, '\n')

(3, 3)
Ejemplo: 
 [[ 0.+4.j  8.-1.j  0.+6.j]
 [ 2.+0.j -4.+4.j 10.-6.j]
 [10.-1.j -2.-2.j  3.+0.j]] 

Transpuesta: 
 [[ 0.+4.j  2.+0.j 10.-1.j]
 [ 8.-1.j -4.+4.j -2.-2.j]
 [ 0.+6.j 10.-6.j  3.+0.j]] 

Conjugada: 
 [[ 0.-4.j  8.+1.j  0.-6.j]
 [ 2.-0.j -4.-4.j 10.+6.j]
 [10.+1.j -2.+2.j  3.-0.j]] 

Adjunta: 
 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 

 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 

 [[ 0.-4.j  2.-0.j 10.+1.j]
 [ 8.+1.j -4.-4.j -2.+2.j]
 [ 0.-6.j 10.+6.j  3.-0.j]] 



# Multiplicacion de matrices

In [36]:
Q = np.array([[4j, 8 - 1j, 6j], [2, -4 + 4j, 10 - 6j], [10 - 1j, -2 - 2j, 3]])
R = np.array([[2j, 8 + 1j, 0], [2, -4 + 4j, 10 - 10j], [10 - 1j, -2 - 2j, 3]])

print('Multiplicacion no conmutativa: \n', np.matmul(Q, R), '\n', np.matmul(R, Q), '\n')
print('Multiplicacion con transpuestas: \n', np.matmul(Q, R).T, '\n', np.matmul(R.T, Q.T), '\n')
print('Multiplicacion con adjuntas: \n', np.matrix(np.matmul(Q, R)).getH(), '\n', np.matmul(np.matrix(R).getH(), np.matrix(Q).getH()), '\n')
#print('Conjugada: \n', Q.conjugate(), '\n')
#print('Adjunta: \n', np.matrix(Q).getH(), '\n\n', Q.T.conjugate(), '\n\n', Q.conjugate().T, '\n')

Multiplicacion no conmutativa: 
 [[ 14.+58.j -20.+56.j  70.-72.j]
 [ 86.-58.j -16.-38.j  30.+62.j]
 [ 28.+13.j  91. -4.j -31. +0.j]] 
 [[  8. +2.j -34.+44.j  74.-38.j]
 [ 82.-94.j -24.-34.j  14.+46.j]
 [ 30.+33.j  89.-24.j -17.+52.j]] 

Multiplicacion con transpuestas: 
 [[ 14.+58.j  86.-58.j  28.+13.j]
 [-20.+56.j -16.-38.j  91. -4.j]
 [ 70.-72.j  30.+62.j -31. +0.j]] 
 [[ 14.+58.j  86.-58.j  28.+13.j]
 [-20.+56.j -16.-38.j  91. -4.j]
 [ 70.-72.j  30.+62.j -31. +0.j]] 

Multiplicacion con adjuntas: 
 [[ 14.-58.j  86.+58.j  28.-13.j]
 [-20.-56.j -16.+38.j  91. +4.j]
 [ 70.+72.j  30.-62.j -31. -0.j]] 
 [[ 14.-58.j  86.+58.j  28.-13.j]
 [-20.-56.j -16.+38.j  91. +4.j]
 [ 70.+72.j  30.-62.j -31. +0.j]] 



# Isomorfismo entre complejos y reales

In [48]:
r1 = 4 
r2 = -5
mat_r = np.array([[r1, r2], [-r2, r1]])
c = 4 - 5j 

s_r = np.array([[-1, 7], [-7, -1]])

print('Sumar elemento: \n', c + (-1 + 7j), '\n', mat_r + s_r, '\n')
print('Elevar al cuadrado: \n', c ** 2, '\n', np.matmul(mat_r, mat_r), '\n')

#ADICION EN FUNCION LINEAL
elemento_a = 7
elemento_b = -2

elemento_c = -1
elemento_d = -2

mat_r1 = np.array([[elemento_a, elemento_b], [-1 * elemento_b, elemento_a]])
mat_r2 = np.array([[elemento_c, elemento_d], [-1 * elemento_d, elemento_c]])

c1 = elemento_a + 1j * elemento_b 
c2 = elemento_c + 1j * elemento_d 

escalar = 10

print('Suma de dos elementos: \n', c1 + c2, '\n', mat_r1 + mat_r2,  '\n')
print('Multiplicacion por escalar real: \n', c1 * escalar, '\n', escalar * mat_r1,  '\n')
print('Multiplicacion de dos elementos: \n', c1 * c2, '\n', np.matmul(mat_r1, mat_r2),  '\n')

Sumar elemento: 
 (3+2j) 
 [[ 3  2]
 [-2  3]] 

Elevar al cuadrado: 
 (-9-40j) 
 [[ -9 -40]
 [ 40  -9]] 

Suma de dos elementos: 
 (6-4j) 
 [[ 6 -4]
 [ 4  6]] 

Multiplicacion por escalar real: 
 (70-20j) 
 [[ 70 -20]
 [ 20  70]] 

Multiplicacion de dos elementos: 
 (-11-12j) 
 [[-11 -12]
 [ 12 -11]] 



# Hadamard Matrix

In [53]:
H = np.array([[1 / 2**0.5, 1 / 2**0.5], [1 / 2**0.5, -1 / 2**0.5]])

print('Hadamard matrix: \n', H, '\n')
print('Hadamard matrix ** 2: \n', H @ H, '\n')
print('Hadamard matrix ** 3: \n', H @ H @ H, '\n')

Hadamard matrix: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 

Hadamard matrix ** 2: 
 [[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]] 

Hadamard matrix ** 3: 
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] 



# Espacio vectorial con Producto Interno

In [67]:
A = np.array([[1j, 4 - 2j], [6, 10j]])
B = np.array([[-3 + 2j, 5], [1j, 2j]])

print('Producto interno no degenerativo: \n', np.vdot(A, A), '\n')
print('Sesgo simetrico: \n', np.vdot(A, B), '\n', np.vdot(B, A).conjugate(), '\n')
print('Producto interno con definicion: \n', np.trace(np.matrix(A).getH() @ B), '\n')
print('Norma o longitud: \n', np.linalg.norm(A), '\n', np.linalg.norm(A) ** 2, '\n')
print('Distancia: \n', np.linalg.norm(A), np.linalg.norm(B), np.linalg.norm(A - B), np.linalg.norm(B - A), '\n')


Producto interno no degenerativo: 
 (157+0j) 

Sesgo simetrico: 
 (42+19j) 
 (42+19j) 

Producto interno con definicion: 
 (42+19j) 

Norma o longitud: 
 12.529964086141668 
 157.0 

Distancia: 
 12.529964086141668 6.557438524302 10.770329614269007 10.770329614269007 

